spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application: 
    name: microservice-config-auguigu-dev
---
spring:
  profiles: test
  application:
    name: microservice-config-auguigu-test
 
